# Generated by Django 5.0.6 on 2024-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('price_per_hour', models.IntegerField()),
                ('available_hours', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
